config/routes.rb
Rails.application.routes.draw do



  resources :hostels
  resources :regions
  get 'last_controller/newLife'

  root 'hostels#index'

  get 'location/index'

  get 'location/show'

  get 'location/create'

  get 'location/new'

  get 'location/edit'

  get 'location/update'

  get 'location/destroy'

  resources :cities
  resources :countries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :region
  has_many :hostels, dependent: :destroy
  validates :name, presence:true, length:{ minimum: 2 }
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'Город успешно добавлен.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'Информация о городе успешно обновлена.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'Город был успешно удалён.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :region_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Название"%> <br>
    <%= form.text_field :name, id: :city_name %>
  </div>

  <div class="field">
    <%= form.label :region_id, "Регион, в котором расположен город" %> <br>
    <%= form.select :region_id, Region.all.collect{|c| [c.name, c.id]} %>
  </div>

  <div class="actions">
    <br>
    <%= form.submit "Сохранить" %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Изменение данных города</h1>

<%= render 'form', city: @city %>

<%= link_to 'Просмотр', @city %> |
<%= link_to 'Вернуться к списку городов', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Города</h1>

<a href= <%=new_city_path%> role="button" class="btn btn-success">
  <span class="glyphicon glyphicon-plus"></span>
  Добавить город
</a>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Название</th>
      <th>Регион</th>
      <th>Действия</th>
    </tr>
  </thead>

  <tbody>
    <% @cities.sort_by{|city|[city.name]}.each do |city| %>
      <tr>
        <td><%= link_to city.name, city %></td>
        <td><%= city.region.name %></td>
        <td>
          <a href= <%=edit_city_path(city)%> role="button" class="btn btn-primary">
            <span class="glyphicon glyphicon-pencil"></span>
          </a>
          <%= link_to 'Удалить', city, method: :delete, data: { confirm: 'Вы уверены?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cities/new.html.erb
<h1>Добавление нового города</h1>

<%= render 'form', city: @city %>

<a href= <%=cities_path%> role="button" class="btn btn-primary">Вернуться к списку городов</a>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название города:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Название региона, в котором расположен город:</strong>
  <%= @city.region.name %>
</p>

<%= link_to 'Изменить данные о регионе', edit_city_path(@city) %> |
<%= link_to 'Вернуться к списку городов', cities_path %>