config/routes.rb
Rails.application.routes.draw do



  resources :hostels
  resources :regions
  get 'last_controller/newLife'

  root 'hostels#index'

  get 'location/index'

  get 'location/show'

  get 'location/create'

  get 'location/new'

  get 'location/edit'

  get 'location/update'

  get 'location/destroy'

  resources :cities
  resources :countries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
  has_many :cities, dependent: :destroy
  validates :name, presence:true, length:{ minimum: 2 }
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Регион успешно добавлен.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Информация о регионе успешно обновлена' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Регион успешно удалён.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name, :country_id)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= form_with(model: region, local: true) do |form| %>
  <% if region.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Название региона" %> <br>
    <%= form.text_field :name, id: :region_name %>
  </div>

  <div class="field">
    <%= form.label :country_id, "Cтрана, в которой расположен регион" %> <br>
    <%= form.select :country_id, Country.all.collect{|c| [c.name, c.id]} %>
  </div>

  <div class="actions">
    <br>
    <%= form.submit "Cохранить" %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<h1>Изменение данных региона</h1>

<%= render 'form', region: @region %>

<%= link_to 'Просмотр', @region %> |
<%= link_to 'Вернуться к списку регионов', regions_path %>

app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Регионы</h1>

<a href= <%=new_region_path%> role="button" class="btn btn-success">
  <span class="glyphicon glyphicon-plus"></span>
  Добавить регион
</a>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Название</th>
      <th>Страна</th>
      <th>Действия</th>
    </tr>
  </thead>

  <tbody>
    <% @regions.sort_by{|region|[region.name]}.each do |region| %>
      <tr>
        <td><%= link_to region.name, region %></td>
        <td><%= region.country.name %></td>
        <td>
          <a href= <%=edit_region_path(region)%> role="button" class="btn btn-primary">
            <span class="glyphicon glyphicon-pencil"></span>
          </a>
          <%= link_to 'Удалить', region, method: :delete, data: { confirm: 'Вы уверены?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/regions/new.html.erb
<h1>Добавление нового региона</h1>

<%= render 'form', region: @region %>

<%= link_to 'Вернуться к списку регионов', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название региона:</strong>
  <%= @region.name %>
</p>

<p>
  <strong>Страна, в которой расположен регион :</strong>
  <%= @region.country.name %>
</p>

<%= link_to 'Изменить данные о регионе', edit_region_path(@region) %> |
<%= link_to 'Вернуться к списку регионов', regions_path %>