config/routes.rb
Rails.application.routes.draw do



  resources :hostels
  resources :regions
  get 'last_controller/newLife'

  root 'hostels#index'

  get 'location/index'

  get 'location/show'

  get 'location/create'

  get 'location/new'

  get 'location/edit'

  get 'location/update'

  get 'location/destroy'

  resources :cities
  resources :countries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hostel.rb
class Hostel < ApplicationRecord
  belongs_to :city
  validates :name, presence:true, length:{ minimum: 2 }
end

app/controllers/hostels_controller.rb
class HostelsController < ApplicationController
  before_action :set_hostel, only: [:show, :edit, :update, :destroy]

  # GET /hostels
  # GET /hostels.json
  def index
    @hostels = Hostel.paginate(:page => params[:page], :per_page => 3)

  end

  # GET /hostels/1
  # GET /hostels/1.json
  def show
  end

  # GET /hostels/new
  def new
    @hostel = Hostel.new
  end

  # GET /hostels/1/edit
  def edit
  end

  # POST /hostels
  # POST /hostels.json
  def create
    @hostel = Hostel.new(hostel_params)

    respond_to do |format|
      if @hostel.save
        format.html { redirect_to @hostel, notice: 'Турбаза успешно добавлена.' }
        format.json { render :show, status: :created, location: @hostel }
      else
        format.html { render :new }
        format.json { render json: @hostel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hostels/1
  # PATCH/PUT /hostels/1.json
  def update
    respond_to do |format|
      if @hostel.update(hostel_params)
        format.html { redirect_to @hostel, notice: 'Информация о турбазе успешно обновлена.' }
        format.json { render :show, status: :ok, location: @hostel }
      else
        format.html { render :edit }
        format.json { render json: @hostel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hostels/1
  # DELETE /hostels/1.json
  def destroy
    @hostel.destroy
    respond_to do |format|
      format.html { redirect_to hostels_url, notice: 'Турбаза успешно удалена.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hostel
      @hostel = Hostel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hostel_params
      params.require(:hostel).permit(:name, :price, :address, :about, :city_id)
    end

end

app/helpers/hostels_helper.rb
module HostelsHelper
end

app/views/hostels/_form.html.erb
<%= form_with(model: hostel, local: true) do |form| %>
  <% if hostel.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h2><%= pluralize(hostel.errors.count, "error") %> prohibited this hostel from being saved:</h2>

      <ul>
      <% hostel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Название" %> <br>
    <%= form.text_field :name, id: :hostel_name %>
  </div>

  <div class="field">
    <%= form.label :price, "Цена, руб." %> <br>
    <%= form.number_field :price, id: :hostel_price, min: 0 %>
  </div>

  <div class="field">
    <%= form.label :address, "Адрес" %> <br>
    <%= form.text_field :address, id: :hostel_address %>
  </div>

  <div class="field">
    <%= form.label :about, "Описание" %> <br>
    <%= form.text_area :about, id: :hostel_about %>
  </div>

  <div class="field">
    <%= form.label :city_id, "Город, в котором расположена турбаза" %> <br>
    <%= form.select :city_id, City.all.collect{|c| [c.name, c.id]} %>
  </div>

  <div class="actions">
    <br>
    <%= form.submit "Сохранить"%>
    <a href= <%=new_hostel_path%> role="button" class="btn btn-success">
      <span class="glyphicon glyphicon-ok"></span>
      Cохранить
    </a>
    <button type="button" сlass="btn btn-success" name="save" value="Сохранить" onClick="return confirmSubmit()">
      <span class="glyphicon glyphicon-ok"></span>
    </button>
  </div>
<% end %>

app/views/hostels/edit.html.erb
<h1>Изменение данных турбазы</h1>

<%= render 'form', hostel: @hostel %>

<a href= <%=hostel_path(@hostel.id)%> role="button" class="btn btn-primary">
  <span class="glyphicon glyphicon-eye-open"></span>
</a>

<a href= <%=hostels_path%> role="button" class="btn btn-primary">
  <span class="glyphicon glyphicon-arrow-left"></span>
  Вернуться к списку турбаз
</a>

app/views/hostels/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Турбазы</h1>

<form class="form-inline">


  <div  align="right">
    <% if @hostels.size > 0 %>
      <%= will_paginate @hostels, renderer: BootstrapPagination::Rails,
                        :previous_label => 'Предыдущий', :next_label => 'Следующий' %>
    <% end %>
  </div>

  <div class="form-group" align="left">
    <a href=<%= new_hostel_path %> role="button" class="btn btn-success">
      <span class="glyphicon glyphicon-plus"></span>
      Добавить турбазу
    </a>
  </div>
</form>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Название</th>
      <th>Цена, руб.</th>
      <th>Страна, Регион, Город</th>
      <th>Адрес</th>
      <th>Описание</th>
      <th>Действия</th>
    </tr>
  </thead>

  <tbody>
    <% @hostels.sort_by{|hostel|[hostel.name]}.each do |hostel| %>
      <tr>
        <td><%= link_to hostel.name, hostel %></td>
        <td><%= hostel.price %></td>
        <td>
          <%= hostel.city.region.country.name %>, <br>
          <%= hostel.city.region.name %>, <br>
          <%= hostel.city.name %>
        </td>
        <td><%= hostel.address %></td>
        <td><%= hostel.about %></td>
        <td>
          <a href= <%=edit_hostel_path(hostel)%> role="button" class="btn btn-primary">
            <span class="glyphicon glyphicon-pencil"></span>
          </a>

          <%= link_to 'Удалить', hostel, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger" %>


        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-group" align="right">
  <% if @hostels.size > 0 %>
    <%= will_paginate @hostels, renderer:BootstrapPagination::Rails,
                      :previous_label=>'Предыдущий',:next_label=>'Следующий' %>
  <% end %>
</div>

app/views/hostels/new.html.erb
<h1>Добавление новой турбазы</h1>

<%= render 'form', hostel: @hostel %>

<a href= <%=hostels_path%> role="button" class="btn btn-primary">
  <span class="glyphicon glyphicon-arrow-left"></span>
  Вернуться к списку турбаз
</a>

app/views/hostels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название турбазы:</strong>
  <%= @hostel.name %>
</p>

<p>
  <strong>Цена, руб.:</strong>
  <%= @hostel.price %>
</p>

<p>
  <strong>Адрес:</strong>
  <%= @hostel.address %>
</p>

<p>
  <strong>Описание:</strong> <br>
  <%= @hostel.about %>
</p>

<p>
  <strong>Название города, в котором расположена турбаза:</strong>
  <%= link_to @hostel.city.name, @hostel.city %>
</p>

<a href= <%=edit_hostel_path(@hostel)%> role="button" class="btn btn-primary">
  <span class="glyphicon glyphicon-pencil"></span>
</a>

<a href= <%=hostels_path%> role="button" class="btn btn-primary">
  <span class="glyphicon glyphicon-arrow-left"></span>
  Вернуться к списку турбаз
</a>