config/routes.rb
Rails.application.routes.draw do



  resources :hostels
  resources :regions
  get 'last_controller/newLife'

  root 'hostels#index'

  get 'location/index'

  get 'location/show'

  get 'location/create'

  get 'location/new'

  get 'location/edit'

  get 'location/update'

  get 'location/destroy'

  resources :cities
  resources :countries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Админка по турбазам</title>
    <%= csrf_meta_tags %>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="row">
      <ul class="nav nav-pills nav-justified">
        <li>
          <a href= <%=hostels_path%> role="button" class="btn btn-secondary">Турбазы</a>
        </li>
        <li>
          <a href=<%=countries_path%> role="button" class="btn btn-secondary">Страны</a>
        </li>
        <li>
          <a href=<%=regions_path%> role="button" class="btn btn-secondary">Регионы</a>
        </li>
        <li>
          <a href=<%=cities_path%> role="button" class="btn btn-secondary">Города</a>
        </li>
      </ul>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>